/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'
import appConfig from './app.config'

export type Locale = 'en' | 'ms-MY'
type Variables = Record<string, string | number>

const en = {
  private: 'Private by design', filesStay: 'Files stay on this device', language: 'Language', pdfMaker: 'ROSES PDF', undo: 'Undo', redo: 'Redo', clear: 'Clear', addFiles: 'Add files',
  dropAnywhere: 'Drop your files anywhere', yourDocument: 'Your document', arrangePages: 'Arrange your pages', buildPdf: 'Create your PDF in 3 steps',
  arrangeHelp: 'Select, edit, and drag pages into place.', emptyHelp: 'Add files, arrange and edit, then export your PDF.', tutorialAdd: 'Add files', tutorialArrange: 'Arrange and edit', tutorialExport: 'Export your PDF', featureTitle: 'Features', featureCombine: 'Combine images and PDF files', featureArrange: 'Reorder, rotate, copy, or remove pages', featureCustomize: 'Add text and images to any page', featurePrivate: 'Work privately in your browser', page: 'page', pages: 'pages',
  selectAll: 'Select all', clearSelection: 'Clear selection', invertSelection: 'Invert selection', selected: '{count} selected', selectBatch: 'Select pages for batch actions', rotate: 'Rotate', grayscale: 'Grayscale', duplicate: 'Duplicate', delete: 'Delete',
  smallThumbs: 'Small thumbnails', mediumThumbs: 'Medium thumbnails', largeThumbs: 'Large thumbnails', dropFiles: 'Drop files here', chooseDevice: 'or click to choose from your device', formats: 'JPEG · PNG · PDF — multiple files welcome', multipleWelcome: 'Multiple files welcome', addMore: 'Add more',
  exportSettings: 'Export settings', makeItYours: 'Settings', pageSize: 'Page size', fitEach: 'Fit each page', a4: 'A4 paper', letter: 'US Letter', orientation: 'Orientation', auto: 'Auto', portrait: 'Portrait', landscape: 'Landscape', margins: 'Margins', none: 'None', narrow: 'Narrow', normal: 'Normal', exportQuality: 'Export quality', small: 'Small', balanced: 'Balanced', best: 'Best', originalQuality: 'Original Quality', emailSharing: 'Email & quick sharing', everyday: 'Everyday quality', printArchive: 'Print & archive', maximumDetail: 'Maximum image detail', recommended: 'Recommended', fileName: 'File name', exportPdf: 'Export PDF', processedLocally: 'Processed entirely in your browser', estimated: '{size} MB est.',
  recovery: 'Project recovery', pickUp: 'Pick up where you left off?', recoveryFound: 'We found {count} saved {pages} from {date}.', discard: 'Discard', restoreProject: 'Restore project',
  deletedOne: '1 page deleted', deletedMany: '{count} pages deleted', dismiss: 'Dismiss', footer: 'Your documents are processed locally in your browser.', footerNote: 'No uploads or account required. Recovery data expires after 24 hours.',
  readingOne: 'Reading 1 file…', readingMany: 'Reading {count} files…', preparing: 'Preparing page {done} of {total}', restoring: 'Restoring your project…', pagesFound: '{name}: {count} pages found', pagesAdded: 'Adding pages… {count} added', largeFileWarning: '{name} is {size} MB. Read this large file?', largePdfWarning: '{name} has {count} pages and is {size} MB. It may use substantial memory. Continue with progressive loading?', importFailed: 'The files could not be imported.',
  recoveryUnavailable: 'Project recovery is unavailable in this browser.', recoverySaveFailed: 'Your project could not be saved for recovery. Browser storage may be full.', recoveryRestoreFailed: 'The saved project could not be restored.', exportFailed: 'The PDF could not be created.', unsupportedFile: '{name}: unsupported format', unreadableFile: '{name}: could not be read', fileTooLarge: '{name}: file exceeds the 500 MB safety limit', tooManyPages: '{name}: PDF exceeds the 2,000-page safety limit', imageTooLarge: '{name}: image exceeds the 100-megapixel safety limit', projectTooLarge: '{name}: adding this file would exceed the 1 GB project limit', removeEveryPage: 'Remove every page and delete its saved recovery data?',
  selectPage: 'Select page {number}', reorderPage: 'Reorder page {number}', openFull: 'Open full view of {name}', openFullTitle: 'Open full view', rotateClockwise: 'Rotate clockwise', toggleGrayscale: 'Toggle grayscale', duplicatePage: 'Duplicate page', removePage: 'Remove page', pdfPage: 'PDF · page {number}', thumbnailSize: 'Thumbnail size',
  fullView: 'Full view of {name}', pageOf: 'Page {current} of {total}', sourcePage: 'source page {number}', zoomControls: 'Zoom controls', zoomOut: 'Zoom out', zoomIn: 'Zoom in', zoomPercent: 'Zoom {percent} percent', fit: 'Fit', closeViewer: 'Close full-page viewer', rendering: 'Rendering high-resolution page…', previousPage: 'Previous page', nextPage: 'Next page', deletePage: 'Delete page', addText: 'Add text', insertImage: 'Insert image',
  moveImage: 'Move inserted image', resizeImage: 'Resize inserted image', resizeCrop: 'Resize free crop frame', moveText: 'Move text', textContent: 'Text content', typeHere: 'Type here', resizeText: 'Resize text box',
  fontFamily: 'Font family', sans: 'Sans', serif: 'Serif', mono: 'Mono', size: 'Size', textColor: 'Text color', backgroundColor: 'Background color', pickColor: 'Pick background color from page', pickColorTitle: 'Pick color from page', opacity: 'Opacity', removeBackground: 'Remove background', noBackground: 'No background', bold: 'Bold', italic: 'Italic', alignLeft: 'Align left', alignCenter: 'Align center', alignRight: 'Align right', duplicateText: 'Duplicate text', deleteText: 'Delete text',
  crop: 'Crop', resetCrop: 'Reset crop', moveBackward: 'Move backward', moveForward: 'Move forward', original: 'Original', free: 'Free', square: '1:1', zoom: 'Zoom', reset: 'Reset', cancel: 'Cancel', apply: 'Apply',
} as const

const ms: Record<keyof typeof en, string> = {
  private: 'Privasi terbina dalam', filesStay: 'Fail kekal pada peranti ini', language: 'Bahasa', pdfMaker: 'ROSES PDF', undo: 'Buat asal', redo: 'Buat semula', clear: 'Kosongkan', addFiles: 'Tambah fail',
  dropAnywhere: 'Lepaskan fail anda di mana-mana', yourDocument: 'Dokumen anda', arrangePages: 'Susun halaman anda', buildPdf: 'Edit PDF anda dalam 3 langkah',
  arrangeHelp: 'Pilih, sunting dan seret halaman ke tempatnya.', emptyHelp: 'Tambah fail, susun dan sunting, kemudian eksport PDF anda.', tutorialAdd: 'Tambah fail', tutorialArrange: 'Susun dan sunting', tutorialExport: 'Eksport PDF anda', featureTitle: 'Ciri-ciri', featureCombine: 'Gabungkan imej dan fail PDF', featureArrange: 'Susun, putar, salin atau buang halaman', featureCustomize: 'Tambah teks dan imej pada mana-mana halaman', featurePrivate: 'Edit secara peribadi dalam pelayar anda', page: 'halaman', pages: 'halaman',
  selectAll: 'Pilih semua', clearSelection: 'Kosongkan pilihan', invertSelection: 'Songsangkan pilihan', selected: '{count} dipilih', selectBatch: 'Pilih halaman untuk tindakan pukal', rotate: 'Putar', grayscale: 'Skala kelabu', duplicate: 'Duplikasi', delete: 'Padam',
  smallThumbs: 'Thumbnail kecil', mediumThumbs: 'Thumbnail sederhana', largeThumbs: 'Thumbnail besar', dropFiles: 'Lepaskan fail di sini', chooseDevice: 'atau klik untuk memilih daripada peranti', formats: 'JPEG · PNG · PDF — berbilang fail diterima', multipleWelcome: 'Berbilang fail diterima', addMore: 'Tambah lagi',
  exportSettings: 'Tetapan eksport', makeItYours: 'Tetapan', pageSize: 'Saiz halaman', fitEach: 'Muat setiap halaman', a4: 'Kertas A4', letter: 'US Letter', orientation: 'Orientasi', auto: 'Auto', portrait: 'Potret', landscape: 'Landskap', margins: 'Margin', none: 'Tiada', narrow: 'Sempit', normal: 'Biasa', exportQuality: 'Kualiti eksport', small: 'Kualiti Rendah (Saiz Kecil)', balanced: 'Seimbang', best: 'Terbaik', originalQuality: 'Kualiti Asal (Saiz Besar)', emailSharing: 'E-mel & perkongsian pantas', everyday: 'Kualiti harian', printArchive: 'Cetak & arkib', maximumDetail: 'Butiran imej maksimum', recommended: 'Disyorkan', fileName: 'Nama fail', exportPdf: 'Eksport PDF', processedLocally: 'Diproses sepenuhnya dalam pelayar anda', estimated: 'anggaran {size} MB',
  recovery: 'Pemulihan projek', pickUp: 'Sambung kerja anda?', recoveryFound: 'Kami menemui {count} {pages} tersimpan dari {date}.', discard: 'Buang', restoreProject: 'Pulihkan projek',
  deletedOne: '1 halaman dipadam', deletedMany: '{count} halaman dipadam', dismiss: 'Tutup', footer: 'Dokumen anda diproses secara setempat dalam pelayar.', footerNote: 'Tiada muat naik atau akaun diperlukan. Data pemulihan luput selepas 24 jam.',
  readingOne: 'Membaca 1 fail…', readingMany: 'Membaca {count} fail…', preparing: 'Menyediakan halaman {done} daripada {total}', restoring: 'Memulihkan projek anda…', pagesFound: '{name}: {count} halaman ditemui', pagesAdded: 'Menambah halaman… {count} ditambah', largeFileWarning: '{name} bersaiz {size} MB. Baca fail besar ini?', largePdfWarning: '{name} mempunyai {count} halaman dan bersaiz {size} MB. Ia mungkin menggunakan banyak memori. Teruskan pemuatan berperingkat?', importFailed: 'Fail tidak dapat diimport.',
  recoveryUnavailable: 'Pemulihan projek tidak tersedia dalam pelayar ini.', recoverySaveFailed: 'Projek anda tidak dapat disimpan untuk pemulihan. Storan pelayar mungkin penuh.', recoveryRestoreFailed: 'Projek tersimpan tidak dapat dipulihkan.', exportFailed: 'PDF tidak dapat dijana.', unsupportedFile: '{name}: format tidak disokong', unreadableFile: '{name}: tidak dapat dibaca', fileTooLarge: '{name}: fail melebihi had keselamatan 500 MB', tooManyPages: '{name}: PDF melebihi had keselamatan 2,000 halaman', imageTooLarge: '{name}: imej melebihi had keselamatan 100 megapiksel', projectTooLarge: '{name}: penambahan fail ini akan melebihi had projek 1 GB', removeEveryPage: 'Buang semua halaman dan padam data pemulihan tersimpan?',
  selectPage: 'Pilih halaman {number}', reorderPage: 'Susun semula halaman {number}', openFull: 'Buka paparan penuh {name}', openFullTitle: 'Buka paparan penuh', rotateClockwise: 'Putar mengikut arah jam', toggleGrayscale: 'Togol skala kelabu', duplicatePage: 'Duplikasi halaman', removePage: 'Buang halaman', pdfPage: 'PDF · halaman {number}', thumbnailSize: 'Saiz thumbnail',
  fullView: 'Paparan penuh {name}', pageOf: 'Halaman {current} daripada {total}', sourcePage: 'halaman sumber {number}', zoomControls: 'Kawalan zoom', zoomOut: 'Zum keluar', zoomIn: 'Zum masuk', zoomPercent: 'Zum {percent} peratus', fit: 'Muat', closeViewer: 'Tutup paparan halaman penuh', rendering: 'Memaparkan halaman resolusi tinggi…', previousPage: 'Halaman sebelumnya', nextPage: 'Halaman seterusnya', deletePage: 'Padam halaman', addText: 'Tambah teks', insertImage: 'Sisip imej',
  moveImage: 'Alih imej sisipan', resizeImage: 'Ubah saiz imej sisipan', resizeCrop: 'Ubah saiz bingkai potong bebas', moveText: 'Alih teks', textContent: 'Kandungan teks', typeHere: 'Taip di sini', resizeText: 'Ubah saiz kotak teks',
  fontFamily: 'Jenis fon', sans: 'Sans', serif: 'Serif', mono: 'Mono', size: 'Saiz', textColor: 'Warna teks', backgroundColor: 'Warna latar', pickColor: 'Pilih warna latar daripada halaman', pickColorTitle: 'Pilih warna daripada halaman', opacity: 'Kelegapan', removeBackground: 'Buang latar', noBackground: 'Tiada latar', bold: 'Tebal', italic: 'Italik', alignLeft: 'Jajar kiri', alignCenter: 'Jajar tengah', alignRight: 'Jajar kanan', duplicateText: 'Duplikasi teks', deleteText: 'Padam teks',
  crop: 'Potong', resetCrop: 'Tetapkan semula potongan', moveBackward: 'Alih ke belakang', moveForward: 'Alih ke hadapan', original: 'Asal', free: 'Bebas', square: '1:1', zoom: 'Zum', reset: 'Tetapkan semula', cancel: 'Batal', apply: 'Terapkan',
}

export type TranslationKey = keyof typeof en
const dictionaries = { en, 'ms-MY': ms }
export const translations = dictionaries
export function translate(locale: Locale, key: TranslationKey, variables: Variables = {}) { let result: string = dictionaries[locale][key] ?? en[key]; for (const [name, value] of Object.entries(variables)) result = result.replaceAll(`{${name}}`, String(value)); return result }
interface I18nValue { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey, variables?: Variables) => string; formatDate: (date: Date) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => { try { const saved = localStorage.getItem('pagecraft-locale'); return saved === 'en' || saved === 'ms-MY' ? saved : appConfig.defaultLocale } catch { return appConfig.defaultLocale } })
  useEffect(() => { document.documentElement.lang = locale; try { localStorage.setItem('pagecraft-locale', locale) } catch { /* Language persistence is optional. */ } }, [locale])
  const value = useMemo<I18nValue>(() => ({ locale, setLocale: setLocaleState, t: (key, variables = {}) => translate(locale, key, variables), formatDate: date => new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(date) }), [locale])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('I18nProvider is missing'); return value }
export const translationKeys = Object.keys(en)
